### ISSUE TITLE
Helvetica

### ISSUE THREAD

**Issue by josephgupkim** [hanyrostom/prj-rev-bwfs-dasmoto#2]
If you wanted to apply Helvetica to multiple styles, there is a simpler way to achieve this. Maybe you know it already or will learn it on the lessons to come but keep in mind to have your code stay D.R.Y.

https://github.com/hanyrostom/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/style.css#L8-L31

**Comment by hanyrostom** [comment]
Got it.. D.R.Y (DONT REPEAT YOURSELF)
