### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by josephgupkim** [hanyrostom/prj-rev-bwfs-dasmoto#3]
Loved the additional comment! My only regret is that I wish it weren't so long on just 1 line. Did you know you could make a comment that's multiple lines? That way, I don't have to scroll so far to the right to read your whole comment!

I would keep placing comments in your code as it helps those reading your code know what's going on in your mind when you were writing it.

https://github.com/hanyrostom/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/style.css#L4-L6

**Comment by hanyrostom** [comment]
AGREE!
