### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [hanyrostom/prj-rev-bwfs-dasmoto#4]
Great job on this project! I know it's only your first one but I'm confident in your ability as we move onto the upcoming lessons/projects!

Just remember to keep your code D.R.Y. and try not to repeat yourself too much (ex. Helvetica).
Loved the comment that was there and glad you were able to do some personal research and learn something new!

Keep up the good work!

Grade: Meets expectation.

**Comment by hanyrostom** [comment]
Thank you Joseph for the Review!
